version: 2.1
jobs:
  build:
    docker:
      -  image: cimg/base:stable
    environment:
      DIGITS: 7777777
    steps:
      - checkout
      - run:
          name: Logging DIGITS ENV variable
          command: echo $DIGITS

workflows:
    run-jobs:
      jobs:
        - build
