version: 2.1
jobs:
  build:
    docker:
      -  image: cimg/base:stable
    environment:
      7DIGITS: 7777777
    steps:
      - checkout
      - run:
          name: Logging 7DIGITS ENV variable
          command: echo $7DIGITS

workflows:
    run-jobs:
      jobs:
        - build
